# Generated by Django 5.0.6 on 2024-06-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('dr_code', models.IntegerField(primary_key=True, serialize=False)),
                ('dr_name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=30)),
                ('date_of_join', models.DateField()),
                ('designation', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
