# Generated by Django 5.0.6 on 2024-06-14 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='admind',
            fields=[
                ('admin_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('user_name', models.CharField(max_length=30)),
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('email_id', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('relative_name', models.CharField(max_length=30)),
                ('relative_address', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
                ('doctor_name', models.CharField(max_length=30)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('email_id', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
