# Generated by Django 5.0.6 on 2024-06-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_admind_login_patient_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='name',
            new_name='names',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='name',
            new_name='uname',
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
